### ISSUE TITLE
Provide an UMD bundle

### ISSUE THREAD

**Issue by jochenberger** [gregthebusker/react-confirm-bootstrap#12]
Currently, the react-confirm-bootstrap is provided as a CommonJS module, but I'd like to be able to use it in an AMD environment.

**Comment by jochenberger** [comment]
@gregthebusker, would you mind creating a new release that includes this change?

**Comment by gregthebusker** [comment]
@jochenberger Done

**Comment by jochenberger** [comment]
Thanks, but I think something went wrong. There's a 3.1.5 tag in git, but only a 4.0.0 release on npm.

**Comment by gregthebusker** [comment]
@jochenberger Sorry about that. You should use the 4.0.0 release
