### ISSUE TITLE
Not working on react 16

### ISSUE THREAD

**Issue by monski** [gregthebusker/react-confirm-bootstrap#17]
currently not hiding on react 16, when cancel / confirm button clicked
`
<Confirm
                                                              onConfirm={confirmDelete}
                                                              body="Are you sure you want delete this Item?"
                                                              confirmText="Confirm Removal"
                                                              visible={false}
                                                              title="Confirm Action">
                                                              <Button bsStyle="danger"><FontAwesome name="trash"}/> Delete</Button>
</Confirm>
`

**Comment by gregthebusker** [comment]
Should be fixed now in version 5.0.0
