### ISSUE TITLE
'event' is undefined when clicking space around modal

### ISSUE THREAD

**Issue by gaikaz** [gregthebusker/react-confirm-bootstrap#22]
I assume it should close the modal when clicking the space around it. When doing so I get `TypeError: Cannot read property 'stopPropagation' of undefined` in Chrome browser.
This is the case even in unmodified example app.

**Comment by jbarcas** [comment]
Same error as @gaikaz.  It seems that there is a problem with the `onClose` handler when you click outside the modal. The same handler works fine when you click on 'Cancel button.

**Comment by gregthebusker** [comment]
Fixed with https://github.com/gregthebusker/react-confirm-bootstrap/commit/61d2969902d427c0cff8dd4933affa0c748a4b2a
