### ISSUE TITLE
Usage on a DropdownButton?

### ISSUE THREAD

**Issue by duckworth** [gregthebusker/react-confirm-bootstrap#28]
Would be great if this could be used on a react-bootstrap DropdownButton. Currently it seems it is limited to children with an onClick, but a DropdownButton uses onSelect.

**Comment by gregthebusker** [comment]
@duckworth You can already add this yourself.  Just add a wrapper to DropdownButton that renames the click handler.  Here's an example using a library I like called `recompose`.  You'll still need to handle the value actually returned from `onSelect` since it's not propagated through.

```
import { renameProp } from 'recompose';

let OnClickDropdownButton = renameProp('onClick', 'onSelect',)(DropdownButton); 
```
