### ISSUE TITLE
Support to not use the default button

### ISSUE THREAD

**Issue by joaohkfaria** [gregthebusker/react-confirm-bootstrap#9]
How can we use just the modal and not using any children? 

I just wanna the modal and set the visibility passing a state through the "visible" prop.

EDIT: And also, needs a "onCancel" prop...

**Comment by gregthebusker** [comment]
You probably don't want to use this component for that.  You can just build your own using React Bootstrap.
Here's their modal component that you may find useful. https://react-bootstrap.github.io/components.html#modals-live
